name: Build Windows

on:
  pull_request:
    branches: [main, feature/fin-partie-reset-affichage-musique]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore MusiqueHockey/MusiqueHockey.sln
      - name: Build
        run: dotnet build MusiqueHockey/MusiqueHockey.sln --configuration Release --no-restore
